spring:
  profiles:
    active: dev

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml


  mail:
    host: smtp.gmail.com
    port: 587
    username: health.assistant.back@gmail.com
    password: yrze lrll auvp zhks
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

